language: node_js
#rvm:
#  - 2.1.5
node_js:
  - 0.12
before_install:
  - rvm install 2.1.5
  - bundle install
  - npm cache clean
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
